#!/bin/bash
app_dir=/app
user_name=`stat -c %U $app_dir`

export HOME=$app_dir
cd $app_dir

for file in .profile.d/*.sh; do
  source $file
done
hash -r

function run() {
    me=`whoami`

    # Change UID/GID only if current user is not /app user
    if [ "$me" != "$user_name" ];
    then
        setuidgid $user_name $(eval echo "$@")
    else
        "$@"
    fi
}

case "$(basename $0)" in
  start)
    chown -R $user_name:$user_name $app_dir

    # Generate supervisord.conf:
    bash procfile-to-supervisord /app/Procfile /app/SCALE > supervisord.conf

    # Create /var/log/app directory
    mkdir -p /var/log/app

    # Display the generated supervisord.conf:
    echo "Generated supervisord.conf:"
    cat -n supervisord.conf

    # Fix permissions
    chown -R $user_name: /var/log/app supervisord.conf

    # Start up the app:
    run supervisord -c supervisord.conf
    ;;
  *)
    run "$@"
    ;;
esac
